# Makefile: keep tabs

SHELL := /bin/bash -l
export SHELL

VENV := ./vtmp/
export VENV

# rockylibux:10-minimal uses 3.12
MIN_PYTHON_VERSION := $(shell basename $$( ls /usr/bin/python3.12 | awk '{print $0; exit}' ) )
export MIN_PYTHON_VERSION

COMMON_VENV := rm -rf $(VENV); \
	$(MIN_PYTHON_VERSION) -m venv $(VENV); \
	source ./$(VENV)bin/activate;

PIP_INSTALL := pip3 -q \
	--require-virtualenv \
	--disable-pip-version-check \
	--no-color install --no-cache-dir

MYPY_INSTALL := types-requests

DO_MYPY := 	$(COMMON_VENV) $(PIP_INSTALL) mypy $(MYPY_INSTALL); mypy --strict --no-incremental

SCRIPTS		:= scripts/

RL_COMMANDS	:= \
	$(SCRIPTS)entrypoint \
	$(SCRIPTS)rl-scan \
	$(SCRIPTS)rl-scan-url

# ==========================
# Code format and verify
# ==========================
prep: clean format check mypy-all

clean:
	rm -rf $(VENV)
	rm -rf .mypy_cache */.mypy_cache

format:
	ruff format $(SCRIPTS) $(RL_COMMANDS)

check:
	ruff check --fix $(SCRIPTS) $(RL_COMMANDS)

mypy-all: mypy-entrypoint mypy-rl-scan mypy-rl-scan-url

mypy-entrypoint:
	$(DO_MYPY) $(SCRIPTS) $(SCRIPTS)entrypoint

mypy-rl-scan:
	$(DO_MYPY) $(SCRIPTS) $(SCRIPTS)rl-scan

mypy-rl-scan-url:
	$(DO_MYPY) $(SCRIPTS) $(SCRIPTS)rl-scan-url
