SHELL := /bin/bash

# We always test against local build docker image

ifdef DOCKER_TAG
    BUILD_VERSION	:= $(DOCKER_TAG)
else
    BUILD_VERSION=latest
endif

IMAGE_BASE	:= reversinglabs/rl-scanner-cloud
IMAGE_NAME	:= $(IMAGE_BASE):$(BUILD_VERSION)

# testing parameters
REPORT_DIR		:= reports
REPORT_VOLUME 	:= -v ./$(REPORT_DIR):/$(REPORT_DIR)
REPORTS 		:= --report-path /$(REPORT_DIR) --pack-safe --report-format all

ARTIFACT_ERR	:= eicarcom2.zip
ARTIFACT_OK		:= bash
IMPORT_URL := https://www.7-zip.org/a/7z2500-x64.exe

# default is my
ENVFILE := .envfile_rl-scanner-cloud.docker-my

ifdef TEST_PLAYGROUND1
	ENVFILE := .envfile_rl-scanner-cloud.docker-playground
endif

ifdef TEST_PLAYGROUND2
	ENVFILE := .envfile_rl-scanner-cloud.docker-playground
endif

ifdef TEST_CANADA
	ENVFILE := .envfile_rl-scanner-cloud.docker-canada
endif

export ENVFILE

# on purpose no := , we want them to be evaluated each time they are referenced.
DATE = $(shell date +%Y%m%d.%H%M%S )
RL_PACKAGE_URL2	= test-project/test-package@$(DATE)
RL_PACKAGE_REPRO= test-project/test-package@$(DATE)?build=repro

COMMON_DOCKER := -i --rm \
	-u $(shell id -u):$(shell id -u ) \
	--env-file=$(HOME)/$(ENVFILE) \
	-v ./input:/input

COMMON_DOCKER_URL := -i --rm \
	-u $(shell id -u):$(shell id -u ) \
	--env-file=$(HOME)/$(ENVFILE)

TEST_COMMON = --purl $(RL_PACKAGE_URL2) \
	--replace --force --debug

TEST_COMMON_REPRO = --purl $(RL_PACKAGE_REPRO) \
	--debug

TEST_PARAMS_SCAN_MY = \
	--rl-portal-server test \
	--rl-portal-org Test \
	--rl-portal-group Default \
	$(TEST_COMMON)

TEST_PARAMS_SCAN_MY_REPRO = \
	--rl-portal-server test \
	--rl-portal-org Test \
	--rl-portal-group Default \
	$(TEST_COMMON_REPRO)

TEST_PARAMS_SCAN_PLAYGROUND = \
	--rl-portal-server playground \
	--rl-portal-org ReversingLabs \
	--rl-portal-group hello \
	$(TEST_COMMON)

TEST_PARAMS_SCAN_PLAYGROUND2 = \
	--rl-portal-host playground.secure.software:443 \
	--rl-portal-org ReversingLabs \
	--rl-portal-group hello \
	$(TEST_COMMON)

TEST_PARAMS_SCAN_CA = \
    --rl-portal-host ca.secure.software \
	--rl-portal-server test2 \
	--rl-portal-org Test2 \
	--rl-portal-group Default \
	$(TEST_COMMON)

# default test setup
TEST_PARAMS_SCAN = $(TEST_PARAMS_SCAN_MY)
TEST_PARAMS_SCAN_REPRO = $(TEST_PARAMS_SCAN_MY_REPRO)

ifdef TEST_PLAYGROUND1
	TEST_PARAMS_SCAN = $(TEST_PARAMS_SCAN_PLAYGROUND)
endif

ifdef TEST_PLAYGROUND2
	TEST_PARAMS_SCAN = $(TEST_PARAMS_SCAN_PLAYGROUND2)
endif

ifdef TEST_CANADA
	TEST_PARAMS_SCAN = $(TEST_PARAMS_SCAN_CA)
endif

# ==========================
# Testing
# ==========================

TESTS = testFail \
	test_err \
	test_err_with_report \
	test_ok_no_report \
	test_ok_with_report \
	test_submit_only \
	test_url_ok_with_report \
	test_ok_with_report_teamcity


# =-------------------------------------------------

test: $(TESTS)

./input/$(ARTIFACT_ERR):
	mkdir -m 777 -p input output tmp
	curl -o ./input/$(ARTIFACT_ERR) -sS https://secure.eicar.org/$(ARTIFACT_ERR)

./input/$(ARTIFACT_OK):
	mkdir -m 777 -p input output tmp
	cp /bin/$(ARTIFACT_OK) ./input/

testFail:
	# we know that specifying no arguments at all should print "Valid commands are" and fail
	-docker run $(COMMON_DOCKER) $(IMAGE_NAME); echo -e -n "Exit code: $$?"
	# we know that specifying no arguments to rl-scan should print usage() and fail
	-docker run $(COMMON_DOCKER) $(IMAGE_NAME) \
		rl-scan; echo -e -n "Exit code: $$?\n"
	# specify al params except file path, this will fail
	-docker run $(COMMON_DOCKER) $(IMAGE_NAME) \
		rl-scan $(TEST_PARAMS_SCAN); echo -e -n "Exit code: $$?\n"; exit $$?

test_ok_no_report: ./input/$(ARTIFACT_OK)
	echo -e "\n## >>" $@
	rm -rf $(REPORT_DIR) && mkdir $(REPORT_DIR)
	docker run $(COMMON_DOCKER) $(IMAGE_NAME) \
		rl-scan $(TEST_PARAMS_SCAN) \
			--file-path=/input/$(ARTIFACT_OK) \
			2>&1 >tmp/$@.out; echo -e -n "Exit code: $$?\n"; cat tmp/$@.out; exit $$?; exit $$?

test_ok_with_report: ./input/$(ARTIFACT_OK)
	echo -e "\n## >>" $@
	rm -rf $(REPORT_DIR) && mkdir $(REPORT_DIR)
	docker run $(COMMON_DOCKER) $(REPORT_VOLUME) $(IMAGE_NAME) \
		rl-scan $(TEST_PARAMS_SCAN) \
			--file-path=/input/$(ARTIFACT_OK) \
			$(REPORTS) \
			2>&1 >tmp/$@.out; echo -e -n "Exit code: $$?\n"; cat tmp/$@.out; exit $$?

test_ok_with_report_teamcity: ./input/$(ARTIFACT_OK)
	echo -e "\n## >>" $@
	rm -rf $(REPORT_DIR) && mkdir $(REPORT_DIR)
	docker run $(COMMON_DOCKER) $(REPORT_VOLUME) $(IMAGE_NAME) \
		rl-scan $(TEST_PARAMS_SCAN) \
			--message-reporter=teamcity \
			--file-path=/input/$(ARTIFACT_OK) \
			$(REPORTS) \
			2>&1 >tmp/$@.out; echo -e -n "Exit code: $$?\n"; cat tmp/$@.out; exit $$?

test_submit_only: ./input/$(ARTIFACT_OK)
	echo -e "\n## >>" $@
	rm -rf $(REPORT_DIR) && mkdir $(REPORT_DIR)
	docker run $(COMMON_DOCKER) $(IMAGE_NAME) \
		rl-scan $(TEST_PARAMS_SCAN) \
			--file-path=/input/$(ARTIFACT_OK) \
			--submit-only \
			2>&1 >tmp/$@.out; echo -e -n "Exit code: $$?\n"; cat tmp/$@.out; exit $$?

test_err: ./input/$(ARTIFACT_ERR)
	echo -e "\n## >>" $@
	rm -rf $(REPORT_DIR) && mkdir $(REPORT_DIR)
	# as we are now scanning a item that makes the scan fail (non zero exit code) we have to ignore the error in the makefile
	-docker run $(COMMON_DOCKER) $(IMAGE_NAME) \
		rl-scan $(TEST_PARAMS_SCAN) \
			--file-path=/input/$(ARTIFACT_ERR) \
			2>&1 >tmp/$@.out; echo -e -n "Exit code: $$?\n"; cat tmp/$@.out; exit $$?

test_err_with_report: ./input/$(ARTIFACT_ERR)
	echo -e "\n## >>" $@
	rm -rf $(REPORT_DIR) && mkdir $(REPORT_DIR)
	# as we are now scanning a item that makes the scan fail (non zero exit code) we have to ignore the error in the makefile
	-docker run $(COMMON_DOCKER) $(REPORT_VOLUME) $(IMAGE_NAME) \
		rl-scan $(TEST_PARAMS_SCAN) \
			--file-path=/input/$(ARTIFACT_ERR) \
			$(REPORTS) \
			2>&1 >tmp/$@.out; echo -e -n "Exit code: $$?\n"; cat tmp/$@.out; exit $$?

# NOTE no input volume
test_url_ok_with_report:
	echo -e "\n## >>" $@
	rm -rf $(REPORT_DIR) && mkdir $(REPORT_DIR)
	docker run $(COMMON_DOCKER_URL) $(REPORT_VOLUME) $(IMAGE_NAME) \
		rl-scan-url $(TEST_PARAMS_SCAN) \
			--import-url=$(IMPORT_URL) \
			$(REPORTS) \
			2>&1 >tmp/$@.out; echo -e -n "Exit code: $$?\n"; cat tmp/$@.out; exit $$?
