#!/usr/bin/env python3
import argparse
import os
from typing import Any

from cimessages import Messages
from constants import (
    DESCRIPTION_TEXT,
    EPILOG_TEXT_URL,
)
from helpers import (
    common_arguments,
    parse_report_formats,
    runner,
    valid_timeout,
    validate_download_auth,
    validate_report_folder,
    validate_server_host,
)
from params import Params
from portal_api import PortalAPI
from post_scan import PostScan


def _collect_params() -> Params:

    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        prog="rl-scan-url",
        description=DESCRIPTION_TEXT,
        epilog=EPILOG_TEXT_URL,
    )

    common_arguments(parser)

    # import url parameters
    parser.add_argument(
        "--import-url",
        required=True,
        help="The url you want to scan",
    )

    au = os.environ.get("RLPORTAL_AUTH_USER", "").strip()
    parser.add_argument(
        "--auth-user",
        help="The auth-user (if needed) to access the import-url; You can also use the env var: RLPORTAL_AUTH_USER",
        default=au,
    )

    ap = os.environ.get("RLPORTAL_AUTH_PASS", "").strip()
    parser.add_argument(
        "--auth-pass",
        help="The auth-password (if needed) to access the import-url; Prefer using the env var: RLPORTAL_AUTH_PASS",
        default=ap,
    )

    bt = os.environ.get("RLPORTAL_BEARER_TOKEN", "").strip()
    parser.add_argument(
        "--bearer-token",
        help="The bearer-token (if needed) to access the import-url; Prefer using the env var: RLPORTAL_BEARER_TOKEN",
        default=bt,
    )

    data: dict[str, Any] = vars(parser.parse_args())
    params = Params(**data)
    validate_server_host(params)

    # --------------------------------
    if params.import_url is None or len(params.import_url) == 0:
        raise RuntimeError("Fatal: you must specify a url to import")

    if params.import_url and "://" not in params.import_url:
        raise RuntimeError("Fatal: --import-url should be url like, it has missing '://'")

    if params.auth_user and params.bearer_token:
        raise RuntimeError("Fatal: --bearer-token cannot be used in combination with --auth-user")

    if params.auth_pass and params.bearer_token:
        raise RuntimeError("Fatal: --bearer-token cannot be used in combination with --auth-pass")
    # --------------------------------

    validate_report_folder(params)
    params.report_format = parse_report_formats(params)
    return params


def main() -> int:
    rr: int = 101
    session = None
    try:
        params: Params = _collect_params()
        reporter = Messages.create(params.message_reporter.value)
        params.timeout = valid_timeout(reporter, params.timeout)
        validate_download_auth(params)
        scanner = PortalAPI(params, reporter)
        session = scanner.session
        scanner.transform_force_and_replace_params()

        # SCAN ------------------------------
        import_url: str = str(params.import_url)
        with reporter.progress_block("Scanning Url version"):
            scanner.scan_import_url_version(import_url=import_url)
            if params.submit_only:
                reporter.info("submit-only flag present, skip waiting for analysis result")
                reporter.show_scan_result(None)
                return 0

        ps = PostScan(
            params=params,
            reporter=reporter,
            scanner=scanner,
        )
        rr = ps.after_scan()
    except Exception as e:
        reporter.error(f"Exception: {e}")
    finally:
        if session:
            session.close()

    return rr


if __name__ == "__main__":
    runner(main)
