#!/usr/bin/env python3
import argparse
import sys
import traceback

from cimessages import (
    MessageFormat,
    reporter,
)
from helpers import (
    get_portal_url,
)
from params import Params
from portal_api import PortalAPI
from post_scan import (
    get_analysis_url,
    get_scan_status,
    export_analysis_report,
    export_pack_safe,
)
from validators import (
    validate_report_formats,
    validate_report_folder,
)
from constants import (
    DEFAULT_ATTEMPT_TIMEOUT_MIN,
    REPORT_FORMATS,
    EXIT_FATAL,
)


def _build_argument_parser() -> Params:
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        prog="rl-scan-url",
        description="ReversingLabs: rl-scanner-cloud\n\n"
        "Extended product documentation is available at: https://docs.secure.software",
        epilog="Environment variables:\n"
        "  RLPORTAL_ACCESS_TOKEN    - Token used for access to the Portal\n"
        "  RLSECURE_PROXY_SERVER    - Server URL for local proxy\n"
        "  RLSECURE_PROXY_PORT      - Network port for local proxy\n"
        "  RLSECURE_PROXY_USER      - User name for proxy authentication\n"
        "  RLSECURE_PROXY_PASSWORD  - Password for proxy authentication\n",
    )

    supportedReports = ", ".join(list(REPORT_FORMATS.keys())) + ", all"

    # portal params
    parser.add_argument(
        "--rl-portal-host",
        help="Portal Host that will do the scanning",
        required=False,
    )

    parser.add_argument(
        "--rl-portal-server",
        help="Portal tenant that will do the scanning",
        required=False,
    )

    parser.add_argument(
        "--rl-portal-org",
        required=True,
    )

    parser.add_argument(
        "--rl-portal-group",
        required=True,
    )

    # common for scan/status/report
    parser.add_argument(
        "--purl",
        required=True,
        help="Package URL used for the scan (format [pkg:namespace]/<project></package><@version>)",
    )

    # scan parameters
    parser.add_argument(
        "--replace",
        action="store_true",
        help="Replace the existing package version within the package, or reproducible build if build type is repro",
    )

    parser.add_argument(
        "--force",
        action="store_true",
        help="If a package has the maximum number of versions, then the oldest version of the package will be "
        "deleted to make space for the version you're uploading",
    )

    parser.add_argument(
        "--submit-only",
        action="store_true",
        help="Scan the file, and continue regardless of the scan outcome",
    )

    parser.add_argument(
        "--diff-with",
        help="Selected analyzed package version to compare against the uploaded version",
    )

    parser.add_argument(
        "--timeout",
        type=int,
        default=DEFAULT_ATTEMPT_TIMEOUT_MIN,
        help="Amount of time user is willing to wait for analysis before failing."
        + f" Defaults to {DEFAULT_ATTEMPT_TIMEOUT_MIN} minutes",
    )

    # messages
    parser.add_argument(
        "--message-reporter",
        choices=list(MessageFormat),
        type=MessageFormat,
        default=MessageFormat.TEXT,
        help="Processing status message format",
    )

    # report parameters
    parser.add_argument(
        "--report-format",
        type=str,
        help="A comma-separated list of report formats to generate. Supported values: " + f"{supportedReports}",
    )

    parser.add_argument(
        "--report-path",
        help="Path to a directory where the selected reports will be saved",
    )

    parser.add_argument(
        "--pack-safe",
        action="store_true",
        help="Download a report.rl-safe archive into the report-path",
    )

    # import url parameters
    parser.add_argument(
        "--import-url",
        required=True,
        help="The url you want to scan",
    )

    parser.add_argument(
        "--auth-user",
        help="The auth-user (if needed) to access the import-url",
    )

    parser.add_argument(
        "--auth-pass",
        help="The auth-password (if needed) to access the import-url",
    )

    parser.add_argument(
        "--bearer-token",
        help="The bearer-token (if needed) to access the import-url",
    )

    # debug
    parser.add_argument(
        "--debug",
        action="store_true",
        help="add additional verbosity during execution",
    )

    # scan additonal params (optional)
    # max_size
    # product
    # publisher
    # category
    # license
    # platform
    # release_date

    params = Params(**vars(parser.parse_args()))
    validate_report_folder(params.report_path, params.report_format)
    validate_report_formats(params.report_format)

    if params.import_url and "://" not in params.import_url:
        raise RuntimeError("--import-url should be url like, it has missing '://'")

    if params.auth_user and params.bearer_token:
        raise RuntimeError("--bearer-token cannot be used in combination with --auth-user")

    if params.auth_pass and params.bearer_token:
        raise RuntimeError("--bearer-token cannot be used in combination with --auth-pass")

    return params


def main() -> int:
    params: Params = _build_argument_parser()

    reporter.set_format(params.message_reporter)
    scanner = PortalAPI(params)

    # SCAN
    assert params.import_url is not None
    import_url: str = params.import_url
    with reporter.progress_block("Scanning Url version"):
        scanner.scan_import_url_version(import_url=import_url)
        if params.submit_only:
            reporter.info("submit-only flag present, skip waiting for analysis result")
            reporter.show_scan_result(None)
            return 0

    # STATUS
    with reporter.progress_block("Fetching analysis status"):
        scan_status = get_scan_status(scanner, params.timeout)
        passed_analysis = scan_status == "pass"
        reporter.show_scan_result(passed_analysis)

    # REPORTS
    with reporter.progress_block("Getting the report URL"):
        analysis_url = get_analysis_url(scanner)
        portal_url = get_portal_url(
            rl_portal_host=params.rl_portal_host,
            rl_portal_server=params.rl_portal_server,
        )
        report_url = f"{portal_url}/{analysis_url}"
        reporter.with_prefix("Report URL", report_url)

    if params.report_format and params.report_path:
        with reporter.progress_block("Exporting analysis report"):
            export_analysis_report(
                scanner,
                params.report_format,
                params.report_path,
            )

    if params.pack_safe and params.report_path:
        with reporter.progress_block("Exporting rl-safe archive"):
            export_pack_safe(
                scanner,
                params.report_path,
            )

    # DONE
    return 0 if passed_analysis else 1


if __name__ == "__main__":
    try:
        rr: int = main()
        sys.exit(rr)
    except Exception as e:
        print(f"Error: rl_scan: {str(e)}")

        if 0:
            try:
                raise TypeError("Again !?!")
            except:
                pass

        traceback.print_tb(e.__traceback__)
        sys.exit(EXIT_FATAL)
