#!/usr/bin/env python3
import argparse
import os
from typing import Any

from cimessages import Messages
from constants import (
    DESCRIPTION_TEXT,
    EPILOG_TEXT,
    GB,
    UPLOAD_FILE_SIZE_LIMIT,
)
from helpers import (
    common_arguments,
    parse_report_formats,
    runner,
    valid_timeout,
    validate_report_folder,
    validate_server_host,
)
from params import Params
from portal_api import PortalAPI
from post_scan import PostScan


def _validate_file_path(
    file_path: str,
) -> None:
    if not os.path.isfile(file_path):
        raise RuntimeError(f"That is not a existing file: {file_path}")

    if os.path.getsize(file_path) > UPLOAD_FILE_SIZE_LIMIT:
        raise RuntimeError(f"File size is larger than {int(UPLOAD_FILE_SIZE_LIMIT / GB)}GB")


def _collect_params() -> Params:
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        prog="rl-scan",
        description=DESCRIPTION_TEXT,
        epilog=EPILOG_TEXT,
    )

    common_arguments(parser)

    parser.add_argument(
        "--file-path",
        required=True,
        help="Path to the file you want to scan",
    )

    parser.add_argument(
        "--filename",
        help="Defaults to the name of the selected file",
    )

    data: dict[str, Any] = vars(parser.parse_args())
    params = Params(**data)
    validate_server_host(params)

    # --------------------------------
    if not params.file_path:
        raise RuntimeError("Fatal: you must specify a file-path")
    _validate_file_path(params.file_path)
    # --------------------------------

    validate_report_folder(params)
    params.report_format = parse_report_formats(params)
    return params


def main() -> int:
    rr: int = 101
    session = None
    try:
        params: Params = _collect_params()
        reporter = Messages.create(params.message_reporter.value)
        params.timeout = valid_timeout(reporter, params.timeout)
        scanner = PortalAPI(params, reporter)
        session = scanner.session
        scanner.transform_force_and_replace_params()

        file_path: str = str(params.file_path)
        file_name: str = params.filename if params.filename else os.path.basename(file_path)

        # SCAN ------------------------------
        with reporter.progress_block("Scanning version"):
            with open(file_path, "rb") as file_stream:
                scanner.scan_file_version(
                    file_stream=file_stream,
                    file_name=file_name,
                )
                if params.submit_only:
                    reporter.info("submit-only flag present, skip waiting for analysis result")
                    reporter.show_scan_result(None)
                    return 0

        ps = PostScan(
            params=params,
            reporter=reporter,
            scanner=scanner,
        )
        rr = ps.after_scan()
    except Exception as e:
        reporter.error(f"Exception: {e}")
    finally:
        if session:
            session.close()

    return rr


if __name__ == "__main__":
    runner(main)
